### ISSUE TITLE
~/CBA/template.rb

### ISSUE THREAD

**Issue by lgs** [iboard/CBA#1]
Hi Andi,

I noticed you started your fine work on CBA, from the useful Rails3-Mongoid-Devise template by fortuity. 

I think should be great and useful if you could update ~/CBA/template.rb with your OmniAuth integration snippets. 

Do you think is possible ?
Thanks
luca

**Comment by iboard** [comment]
Hi Luca,

thank you. Sure, this is scheduled for this weekend. But before I will fix and review the design of the "commentable-stuff", and then, when everything works fine, I will trigger template.rb. Should be on github until Wednesday.

Have fun!

**Comment by iboard** [comment]
Sorry, this issue can not be solved this week. But it's mentioned in PivotalTracker and I will not forget ;-)

**Comment by iboard** [comment]
I finished the first version of <code>installation.rb</code>. Please read the Wiki for instructions.

**Comment by lgs** [comment]
That's very useful Andi.

I just tried on my Linux ubuntu 10.04 with rvm => ruby-1.9.2-p136 [ i386 ], it works fine. Here's the output: http://pastie.org/1550420

Thanks for sharing.
Luca G. Soave
