### ISSUE TITLE
New Posting page: :html_template_label has odd formatting

### ISSUE THREAD

**Issue by tbbooher** [iboard/CBA#19]
The new posting page has odd formatting, especially with the html_template_label

http://cba.iboard.cc/blogs/4e6f5ca3daf9851c33000018/postings/new

What is the purpose of this label? It clearly is intended to display as raw, but even then I'm not sure what it is for.

**Comment by iboard** [comment]
This help for placeholders should not be displayed with new posting form. It makes sense for Page only.
Thank you! I've removed this from postings/_form.
